---
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.55.4/hugo_0.55.4_Linux-64bit.deb
  - sudo dpkg -i hugo_0.55.4_Linux-64bit.deb
script:
  - hugo
deploy:
  - provider: script
    script:
    - git clone --branch=devops https://github.com/vmware/singleton.git devops
    - cd $TRAVIS_BUILD_DIR/devops/deploy/documentation/ && ./publish_to_ghpages.sh
    skip_cleanup: true
    keep_history: true
    on:
      branch: website